services:
  - type: web
    name: flight-booking-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_conf.py run:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production
      - key: API_BASE_URL
        value: https://flight-booking-with-dynamic-pricing.onrender.com/api
    healthCheckPath: /
    region: oregon