services:
  - type: web
    name: flight-booking-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_conf.py --worker-class uvicorn.workers.UvicornWorker --timeout 120 run:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production
      - key: ROOT_PATH
        value: ""
    healthCheckPath: /api
    region: oregon