"""
Airline and airport data
"""

# AIRLINE CODE TO NAME MAPPING (IATA codes)
AIRLINE_NAMES = {
    "AA": "American Airlines",
    "DL": "Delta Air Lines",
    "UA": "United Airlines",
    "WN": "Southwest Airlines",
    "B6": "JetBlue Airways",
    "AS": "Alaska Airlines",
    "NK": "Spirit Airlines",
    "F9": "Frontier Airlines",
    "HA": "Hawaiian Airlines",
    "G4": "Allegiant Air",
    "SY": "Sun Country Airlines",
    "VX": "Virgin America",
    "BA": "British Airways",
    "LH": "Lufthansa",
    "AF": "Air France",
    "KL": "KLM Royal Dutch Airlines",
    "IB": "Iberia",
    "AZ": "ITA Airways",
    "LX": "Swiss International Air Lines",
    "OS": "Austrian Airlines",
    "SN": "Brussels Airlines",
    "EI": "Aer Lingus",
    "SK": "Scandinavian Airlines",
    "AY": "Finnair",
    "TP": "TAP Air Portugal",
    "EK": "Emirates",
    "QR": "Qatar Airways",
    "EY": "Etihad Airways",
    "SV": "Saudia",
    "MS": "EgyptAir",
    "TK": "Turkish Airlines",
    "JL": "Japan Airlines",
    "NH": "All Nippon Airways",
    "KE": "Korean Air",
    "OZ": "Asiana Airlines",
    "CA": "Air China",
    "MU": "China Eastern Airlines",
    "CZ": "China Southern Airlines",
    "SQ": "Singapore Airlines",
    "TG": "Thai Airways",
    "MH": "Malaysia Airlines",
    "AI": "Air India",
    "9W": "Jet Airways",
    "QF": "Qantas",
    "NZ": "Air New Zealand",
    "LA": "LATAM Airlines",
    "AM": "Aeroméxico",
    "CM": "Copa Airlines",
    "AV": "Avianca",
    "AR": "Aerolíneas Argentinas",
    "SA": "South African Airways",
    "ET": "Ethiopian Airlines",
    "KQ": "Kenya Airways",
    "U2": "easyJet",
    "FR": "Ryanair",
    "W6": "Wizz Air",
    "VY": "Vueling",
    "U9": "Tatarstan Airlines",
    "HU": "Hainan Airlines",
    "3U": "Sichuan Airlines",
    "MF": "Xiamen Airlines"
}

def get_airline_name(code: str) -> str:
    """Convert airline code to full name"""
    return AIRLINE_NAMES.get(code, f"Unknown Airline ({code})")